// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next';

// https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables
const API_KEY = process.env.API_KEY;

type Data = {
  recipe: Object | null;
};

// Sample of data returns for reference
const sampleData = {
  vegetarian: true,
  vegan: false,
  glutenFree: true,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 18,
  gaps: 'no',
  lowFodmap: false,
  aggregateLikes: 1,
  spoonacularScore: 41.0,
  healthScore: 6.0,
  creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
  license: 'CC BY 3.0',
  sourceName: 'Foodista',
  pricePerServing: 78.43,
  extendedIngredients: [
    {
      id: 19296,
      aisle: 'Nut butters, Jams, and Honey',
      image: 'honey.png',
      consistency: 'liquid',
      name: 'honey',
      nameClean: 'honey',
      original: '1 cup honey',
      originalString: '1 cup honey',
      originalName: 'honey',
      amount: 1.0,
      unit: 'cup',
      meta: [],
      metaInformation: [],
      measures: {
        us: { amount: 1.0, unitShort: 'cup', unitLong: 'cup' },
        metric: { amount: 236.588, unitShort: 'ml', unitLong: 'milliliters' },
      },
    },
    {
      id: 1085,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'milk.jpg',
      consistency: 'liquid',
      name: 'non-fat milk',
      nameClean: 'fat free milk',
      original: '2 cups non-fat dry milk',
      originalString: '2 cups non-fat dry milk',
      originalName: 'non-fat dry milk',
      amount: 2.0,
      unit: 'cups',
      meta: ['dry'],
      metaInformation: ['dry'],
      measures: {
        us: { amount: 2.0, unitShort: 'cups', unitLong: 'cups' },
        metric: { amount: 473.176, unitShort: 'ml', unitLong: 'milliliters' },
      },
    },
    {
      id: 16098,
      aisle: 'Nut butters, Jams, and Honey',
      image: 'peanut-butter.png',
      consistency: 'solid',
      name: 'peanut butter',
      nameClean: 'peanut butter',
      original: '1 cup peanut butter',
      originalString: '1 cup peanut butter',
      originalName: 'peanut butter',
      amount: 1.0,
      unit: 'cup',
      meta: [],
      metaInformation: [],
      measures: {
        us: { amount: 1.0, unitShort: 'cup', unitLong: 'cup' },
        metric: { amount: 236.588, unitShort: 'ml', unitLong: 'milliliters' },
      },
    },
    {
      id: 19336,
      aisle: 'Baking',
      image: 'powdered-sugar.jpg',
      consistency: 'solid',
      name: 'powdered sugar',
      nameClean: 'powdered sugar',
      original: '1 cup powdered sugar',
      originalString: '1 cup powdered sugar',
      originalName: 'powdered sugar',
      amount: 1.0,
      unit: 'cup',
      meta: [],
      metaInformation: [],
      measures: {
        us: { amount: 1.0, unitShort: 'cup', unitLong: 'cup' },
        metric: { amount: 236.588, unitShort: 'ml', unitLong: 'milliliters' },
      },
    },
  ],
  id: 664089,
  title: 'Turkish Delight',
  readyInMinutes: 45,
  servings: 8,
  sourceUrl: 'http://www.foodista.com/recipe/2SBR8JHN/turkish-delight',
  image: 'https://spoonacular.com/recipeImages/664089-556x370.jpg',
  imageType: 'jpg',
  nutrition: {
    nutrients: [
      {
        name: 'Calories',
        title: 'Calories',
        amount: 397.63,
        unit: 'kcal',
        percentOfDailyNeeds: 19.88,
      },
      {
        name: 'Fat',
        title: 'Fat',
        amount: 16.3,
        unit: 'g',
        percentOfDailyNeeds: 25.08,
      },
      {
        name: 'Saturated Fat',
        title: 'Saturated Fat',
        amount: 3.42,
        unit: 'g',
        percentOfDailyNeeds: 21.4,
      },
      {
        name: 'Carbohydrates',
        title: 'Carbohydrates',
        amount: 59.23,
        unit: 'g',
        percentOfDailyNeeds: 19.74,
      },
      {
        name: 'Net Carbohydrates',
        title: 'Net Carbohydrates',
        amount: 57.21,
        unit: 'g',
        percentOfDailyNeeds: 20.8,
      },
      {
        name: 'Sugar',
        title: 'Sugar',
        amount: 55.56,
        unit: 'g',
        percentOfDailyNeeds: 61.73,
      },
      {
        name: 'Cholesterol',
        title: 'Cholesterol',
        amount: 1.23,
        unit: 'mg',
        percentOfDailyNeeds: 0.41,
      },
      {
        name: 'Sodium',
        title: 'Sodium',
        amount: 175.75,
        unit: 'mg',
        percentOfDailyNeeds: 7.64,
      },
      {
        name: 'Protein',
        title: 'Protein',
        amount: 10.28,
        unit: 'g',
        percentOfDailyNeeds: 20.57,
      },
      {
        name: 'Manganese',
        title: 'Manganese',
        amount: 0.51,
        unit: 'mg',
        percentOfDailyNeeds: 25.46,
      },
      {
        name: 'Vitamin B3',
        title: 'Vitamin B3',
        amount: 4.43,
        unit: 'mg',
        percentOfDailyNeeds: 22.16,
      },
      {
        name: 'Vitamin E',
        title: 'Vitamin E',
        amount: 2.91,
        unit: 'mg',
        percentOfDailyNeeds: 19.37,
      },
      {
        name: 'Phosphorus',
        title: 'Phosphorus',
        amount: 179.01,
        unit: 'mg',
        percentOfDailyNeeds: 17.9,
      },
      {
        name: 'Magnesium',
        title: 'Magnesium',
        amount: 57.25,
        unit: 'mg',
        percentOfDailyNeeds: 14.31,
      },
      {
        name: 'Vitamin B6',
        title: 'Vitamin B6',
        amount: 0.21,
        unit: 'mg',
        percentOfDailyNeeds: 10.4,
      },
      {
        name: 'Vitamin B2',
        title: 'Vitamin B2',
        amount: 0.16,
        unit: 'mg',
        percentOfDailyNeeds: 9.66,
      },
      {
        name: 'Potassium',
        title: 'Potassium',
        amount: 327.19,
        unit: 'mg',
        percentOfDailyNeeds: 9.35,
      },
      {
        name: 'Calcium',
        title: 'Calcium',
        amount: 91.29,
        unit: 'mg',
        percentOfDailyNeeds: 9.13,
      },
      {
        name: 'Copper',
        title: 'Copper',
        amount: 0.18,
        unit: 'mg',
        percentOfDailyNeeds: 8.84,
      },
      {
        name: 'Zinc',
        title: 'Zinc',
        amount: 1.29,
        unit: 'mg',
        percentOfDailyNeeds: 8.6,
      },
      {
        name: 'Fiber',
        title: 'Fiber',
        amount: 2.02,
        unit: 'g',
        percentOfDailyNeeds: 8.08,
      },
      {
        name: 'Folate',
        title: 'Folate',
        amount: 27.78,
        unit: 'µg',
        percentOfDailyNeeds: 6.94,
      },
      {
        name: 'Selenium',
        title: 'Selenium',
        amount: 4.13,
        unit: 'µg',
        percentOfDailyNeeds: 5.91,
      },
      {
        name: 'Vitamin B5',
        title: 'Vitamin B5',
        amount: 0.59,
        unit: 'mg',
        percentOfDailyNeeds: 5.89,
      },
      {
        name: 'Vitamin B12',
        title: 'Vitamin B12',
        amount: 0.31,
        unit: 'µg',
        percentOfDailyNeeds: 5.1,
      },
      {
        name: 'Vitamin D',
        title: 'Vitamin D',
        amount: 0.74,
        unit: 'µg',
        percentOfDailyNeeds: 4.9,
      },
      {
        name: 'Iron',
        title: 'Iron',
        amount: 0.81,
        unit: 'mg',
        percentOfDailyNeeds: 4.49,
      },
      {
        name: 'Vitamin B1',
        title: 'Vitamin B1',
        amount: 0.05,
        unit: 'mg',
        percentOfDailyNeeds: 3.41,
      },
      {
        name: 'Vitamin A',
        title: 'Vitamin A',
        amount: 124.95,
        unit: 'IU',
        percentOfDailyNeeds: 2.5,
      },
    ],
    properties: [
      {
        name: 'Glycemic Index',
        title: 'Glycemic Index',
        amount: 12.44,
        unit: '',
      },
      {
        name: 'Glycemic Load',
        title: 'Glycemic Load',
        amount: 19.83,
        unit: '',
      },
    ],
    flavonoids: [
      { name: 'Cyanidin', title: 'Cyanidin', amount: 0.0, unit: '' },
      { name: 'Petunidin', title: 'Petunidin', amount: 0.0, unit: '' },
      { name: 'Delphinidin', title: 'Delphinidin', amount: 0.0, unit: '' },
      { name: 'Malvidin', title: 'Malvidin', amount: 0.0, unit: '' },
      { name: 'Pelargonidin', title: 'Pelargonidin', amount: 0.0, unit: '' },
      { name: 'Peonidin', title: 'Peonidin', amount: 0.0, unit: '' },
      { name: 'Catechin', title: 'Catechin', amount: 0.0, unit: '' },
      {
        name: 'Epigallocatechin',
        title: 'Epigallocatechin',
        amount: 0.0,
        unit: '',
      },
      { name: 'Epicatechin', title: 'Epicatechin', amount: 0.0, unit: '' },
      {
        name: 'Epicatechin 3-gallate',
        title: 'Epicatechin 3-gallate',
        amount: 0.0,
        unit: '',
      },
      {
        name: 'Epigallocatechin 3-gallate',
        title: 'Epigallocatechin 3-gallate',
        amount: 0.0,
        unit: '',
      },
      { name: 'Theaflavin', title: 'Theaflavin', amount: 0.0, unit: '' },
      { name: 'Thearubigins', title: 'Thearubigins', amount: 0.0, unit: '' },
      { name: 'Eriodictyol', title: 'Eriodictyol', amount: 0.0, unit: '' },
      { name: 'Hesperetin', title: 'Hesperetin', amount: 0.0, unit: '' },
      { name: 'Naringenin', title: 'Naringenin', amount: 0.0, unit: '' },
      { name: 'Apigenin', title: 'Apigenin', amount: 0.0, unit: '' },
      { name: 'Luteolin', title: 'Luteolin', amount: 0.0, unit: '' },
      { name: 'Isorhamnetin', title: 'Isorhamnetin', amount: 0.0, unit: '' },
      { name: 'Kaempferol', title: 'Kaempferol', amount: 0.0, unit: '' },
      { name: 'Myricetin', title: 'Myricetin', amount: 0.0, unit: '' },
      { name: 'Quercetin', title: 'Quercetin', amount: 0.0, unit: '' },
      {
        name: "Theaflavin-3,3'-digallate",
        title: "Theaflavin-3,3'-digallate",
        amount: 0.0,
        unit: '',
      },
      {
        name: "Theaflavin-3'-gallate",
        title: "Theaflavin-3'-gallate",
        amount: 0.0,
        unit: '',
      },
      {
        name: 'Theaflavin-3-gallate',
        title: 'Theaflavin-3-gallate',
        amount: 0.0,
        unit: '',
      },
      { name: 'Gallocatechin', title: 'Gallocatechin', amount: 0.0, unit: '' },
    ],
    ingredients: [
      {
        id: 19296,
        name: 'honey',
        amount: 0.13,
        unit: 'cup',
        nutrients: [
          {
            title: 'Cholesterol',
            name: 'Cholesterol',
            amount: 0.0,
            unit: 'mg',
          },
          {
            title: 'Saturated Fat',
            name: 'Saturated Fat',
            amount: 0.0,
            unit: 'g',
          },
          { title: 'Phosphorus', name: 'Phosphorus', amount: 1.7, unit: 'mg' },
          { title: 'Choline', name: 'Choline', amount: 0.93, unit: 'mg' },
          { title: 'Fat', name: 'Fat', amount: 0.0, unit: 'g' },
          { title: 'Caffeine', name: 'Caffeine', amount: 0.0, unit: 'mg' },
          {
            title: 'Poly Unsaturated Fat',
            name: 'Poly Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
          },
          { title: 'Fiber', name: 'Fiber', amount: 0.08, unit: 'g' },
          { title: 'Calories', name: 'Calories', amount: 128.82, unit: 'kcal' },
          {
            title: 'Mono Unsaturated Fat',
            name: 'Mono Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
          },
          { title: 'Zinc', name: 'Zinc', amount: 0.09, unit: 'mg' },
          { title: 'Folic Acid', name: 'Folic Acid', amount: 0.0, unit: 'µg' },
          { title: 'Fluoride', name: 'Fluoride', amount: 2.97, unit: 'mg' },
          { title: 'Vitamin B3', name: 'Vitamin B3', amount: 0.05, unit: 'mg' },
          { title: 'Vitamin A', name: 'Vitamin A', amount: 0.0, unit: 'IU' },
          { title: 'Vitamin B1', name: 'Vitamin B1', amount: 0.0, unit: 'mg' },
          { title: 'Copper', name: 'Copper', amount: 0.02, unit: 'mg' },
          { title: 'Vitamin B5', name: 'Vitamin B5', amount: 0.03, unit: 'mg' },
          { title: 'Iron', name: 'Iron', amount: 0.18, unit: 'mg' },
          { title: 'Magnesium', name: 'Magnesium', amount: 0.85, unit: 'mg' },
          { title: 'Vitamin E', name: 'Vitamin E', amount: 0.0, unit: 'mg' },
          { title: 'Protein', name: 'Protein', amount: 0.13, unit: 'g' },
          { title: 'Vitamin B6', name: 'Vitamin B6', amount: 0.01, unit: 'mg' },
          { title: 'Sodium', name: 'Sodium', amount: 1.7, unit: 'mg' },
          { title: 'Vitamin D', name: 'Vitamin D', amount: 0.0, unit: 'µg' },
          {
            title: 'Vitamin B12',
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
          },
          {
            title: 'Carbohydrates',
            name: 'Carbohydrates',
            amount: 34.92,
            unit: 'g',
          },
          {
            title: 'Net Carbohydrates',
            name: 'Net Carbohydrates',
            amount: 34.83,
            unit: 'g',
          },
          { title: 'Vitamin B2', name: 'Vitamin B2', amount: 0.02, unit: 'mg' },
          { title: 'Vitamin K', name: 'Vitamin K', amount: 0.0, unit: 'µg' },
          { title: 'Potassium', name: 'Potassium', amount: 22.04, unit: 'mg' },
          { title: 'Alcohol', name: 'Alcohol', amount: 0.0, unit: 'g' },
          { title: 'Sugar', name: 'Sugar', amount: 34.8, unit: 'g' },
          { title: 'Selenium', name: 'Selenium', amount: 0.34, unit: 'µg' },
          { title: 'Folate', name: 'Folate', amount: 0.85, unit: 'µg' },
          { title: 'Manganese', name: 'Manganese', amount: 0.03, unit: 'mg' },
          { title: 'Calcium', name: 'Calcium', amount: 2.54, unit: 'mg' },
          { title: 'Vitamin C', name: 'Vitamin C', amount: 0.21, unit: 'mg' },
        ],
      },
      {
        id: 1085,
        name: 'non-fat milk',
        amount: 0.25,
        unit: 'cups',
        nutrients: [
          {
            title: 'Cholesterol',
            name: 'Cholesterol',
            amount: 1.23,
            unit: 'mg',
          },
          {
            title: 'Saturated Fat',
            name: 'Saturated Fat',
            amount: 0.03,
            unit: 'g',
          },
          {
            title: 'Phosphorus',
            name: 'Phosphorus',
            amount: 61.86,
            unit: 'mg',
          },
          { title: 'Choline', name: 'Choline', amount: 9.56, unit: 'mg' },
          { title: 'Fat', name: 'Fat', amount: 0.05, unit: 'g' },
          { title: 'Caffeine', name: 'Caffeine', amount: 0.0, unit: 'mg' },
          {
            title: 'Poly Unsaturated Fat',
            name: 'Poly Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
          },
          { title: 'Fiber', name: 'Fiber', amount: 0.0, unit: 'g' },
          { title: 'Calories', name: 'Calories', amount: 20.83, unit: 'kcal' },
          {
            title: 'Mono Unsaturated Fat',
            name: 'Mono Unsaturated Fat',
            amount: 0.01,
            unit: 'g',
          },
          { title: 'Zinc', name: 'Zinc', amount: 0.26, unit: 'mg' },
          { title: 'Folic Acid', name: 'Folic Acid', amount: 0.0, unit: 'µg' },
          { title: 'Fluoride', name: 'Fluoride', amount: 1.9, unit: 'mg' },
          { title: 'Vitamin B3', name: 'Vitamin B3', amount: 0.06, unit: 'mg' },
          { title: 'Vitamin A', name: 'Vitamin A', amount: 124.95, unit: 'IU' },
          { title: 'Vitamin B1', name: 'Vitamin B1', amount: 0.03, unit: 'mg' },
          { title: 'Copper', name: 'Copper', amount: 0.01, unit: 'mg' },
          { title: 'Vitamin B5', name: 'Vitamin B5', amount: 0.22, unit: 'mg' },
          { title: 'Iron', name: 'Iron', amount: 0.02, unit: 'mg' },
          { title: 'Magnesium', name: 'Magnesium', amount: 6.74, unit: 'mg' },
          { title: 'Vitamin E', name: 'Vitamin E', amount: 0.01, unit: 'mg' },
          { title: 'Protein', name: 'Protein', amount: 2.06, unit: 'g' },
          { title: 'Vitamin B6', name: 'Vitamin B6', amount: 0.02, unit: 'mg' },
          { title: 'Sodium', name: 'Sodium', amount: 25.73, unit: 'mg' },
          { title: 'Vitamin D', name: 'Vitamin D', amount: 0.74, unit: 'µg' },
          {
            title: 'Vitamin B12',
            name: 'Vitamin B12',
            amount: 0.31,
            unit: 'µg',
          },
          {
            title: 'Carbohydrates',
            name: 'Carbohydrates',
            amount: 3.04,
            unit: 'g',
          },
          {
            title: 'Net Carbohydrates',
            name: 'Net Carbohydrates',
            amount: 3.04,
            unit: 'g',
          },
          { title: 'Vitamin B2', name: 'Vitamin B2', amount: 0.11, unit: 'mg' },
          { title: 'Vitamin K', name: 'Vitamin K', amount: 0.0, unit: 'µg' },
          { title: 'Potassium', name: 'Potassium', amount: 95.55, unit: 'mg' },
          { title: 'Alcohol', name: 'Alcohol', amount: 0.0, unit: 'g' },
          { title: 'Sugar', name: 'Sugar', amount: 3.12, unit: 'g' },
          { title: 'Selenium', name: 'Selenium', amount: 1.9, unit: 'µg' },
          { title: 'Folate', name: 'Folate', amount: 3.06, unit: 'µg' },
          { title: 'Manganese', name: 'Manganese', amount: 0.0, unit: 'mg' },
          { title: 'Calcium', name: 'Calcium', amount: 74.72, unit: 'mg' },
          { title: 'Vitamin C', name: 'Vitamin C', amount: 0.0, unit: 'mg' },
        ],
      },
      {
        id: 16098,
        name: 'peanut butter',
        amount: 0.13,
        unit: 'cup',
        nutrients: [
          {
            title: 'Cholesterol',
            name: 'Cholesterol',
            amount: 0.0,
            unit: 'mg',
          },
          {
            title: 'Saturated Fat',
            name: 'Saturated Fat',
            amount: 3.39,
            unit: 'g',
          },
          {
            title: 'Phosphorus',
            name: 'Phosphorus',
            amount: 115.46,
            unit: 'mg',
          },
          { title: 'Choline', name: 'Choline', amount: 20.32, unit: 'mg' },
          { title: 'Fat', name: 'Fat', amount: 16.25, unit: 'g' },
          { title: 'Caffeine', name: 'Caffeine', amount: 0.0, unit: 'mg' },
          {
            title: 'Poly Unsaturated Fat',
            name: 'Poly Unsaturated Fat',
            amount: 4.57,
            unit: 'g',
          },
          { title: 'Fiber', name: 'Fiber', amount: 1.94, unit: 'g' },
          { title: 'Calories', name: 'Calories', amount: 189.63, unit: 'kcal' },
          {
            title: 'Mono Unsaturated Fat',
            name: 'Mono Unsaturated Fat',
            amount: 7.81,
            unit: 'g',
          },
          { title: 'Zinc', name: 'Zinc', amount: 0.94, unit: 'mg' },
          { title: 'Folic Acid', name: 'Folic Acid', amount: 0.0, unit: 'µg' },
          { title: 'Fluoride', name: 'Fluoride', amount: 1.0, unit: 'mg' },
          { title: 'Vitamin B3', name: 'Vitamin B3', amount: 4.32, unit: 'mg' },
          { title: 'Vitamin A', name: 'Vitamin A', amount: 0.0, unit: 'IU' },
          { title: 'Vitamin B1', name: 'Vitamin B1', amount: 0.02, unit: 'mg' },
          { title: 'Copper', name: 'Copper', amount: 0.15, unit: 'mg' },
          { title: 'Vitamin B5', name: 'Vitamin B5', amount: 0.34, unit: 'mg' },
          { title: 'Iron', name: 'Iron', amount: 0.6, unit: 'mg' },
          { title: 'Magnesium', name: 'Magnesium', amount: 49.67, unit: 'mg' },
          { title: 'Vitamin E', name: 'Vitamin E', amount: 2.9, unit: 'mg' },
          { title: 'Protein', name: 'Protein', amount: 8.09, unit: 'g' },
          { title: 'Vitamin B6', name: 'Vitamin B6', amount: 0.18, unit: 'mg' },
          { title: 'Sodium', name: 'Sodium', amount: 148.03, unit: 'mg' },
          { title: 'Vitamin D', name: 'Vitamin D', amount: 0.0, unit: 'µg' },
          {
            title: 'Vitamin B12',
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
          },
          {
            title: 'Carbohydrates',
            name: 'Carbohydrates',
            amount: 6.31,
            unit: 'g',
          },
          {
            title: 'Net Carbohydrates',
            name: 'Net Carbohydrates',
            amount: 4.37,
            unit: 'g',
          },
          { title: 'Vitamin B2', name: 'Vitamin B2', amount: 0.03, unit: 'mg' },
          { title: 'Vitamin K', name: 'Vitamin K', amount: 0.19, unit: 'µg' },
          { title: 'Potassium', name: 'Potassium', amount: 209.3, unit: 'mg' },
          { title: 'Alcohol', name: 'Alcohol', amount: 0.0, unit: 'g' },
          { title: 'Sugar', name: 'Sugar', amount: 2.97, unit: 'g' },
          { title: 'Selenium', name: 'Selenium', amount: 1.81, unit: 'µg' },
          { title: 'Folate', name: 'Folate', amount: 23.87, unit: 'µg' },
          { title: 'Manganese', name: 'Manganese', amount: 0.47, unit: 'mg' },
          { title: 'Calcium', name: 'Calcium', amount: 13.87, unit: 'mg' },
          { title: 'Vitamin C', name: 'Vitamin C', amount: 0.0, unit: 'mg' },
        ],
      },
      {
        id: 19336,
        name: 'powdered sugar',
        amount: 0.13,
        unit: 'cup',
        nutrients: [
          {
            title: 'Cholesterol',
            name: 'Cholesterol',
            amount: 0.0,
            unit: 'mg',
          },
          {
            title: 'Saturated Fat',
            name: 'Saturated Fat',
            amount: 0.0,
            unit: 'g',
          },
          { title: 'Phosphorus', name: 'Phosphorus', amount: 0.0, unit: 'mg' },
          { title: 'Choline', name: 'Choline', amount: 0.0, unit: 'mg' },
          { title: 'Fat', name: 'Fat', amount: 0.0, unit: 'g' },
          { title: 'Caffeine', name: 'Caffeine', amount: 0.0, unit: 'mg' },
          {
            title: 'Poly Unsaturated Fat',
            name: 'Poly Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
          },
          { title: 'Fiber', name: 'Fiber', amount: 0.0, unit: 'g' },
          { title: 'Calories', name: 'Calories', amount: 58.35, unit: 'kcal' },
          {
            title: 'Mono Unsaturated Fat',
            name: 'Mono Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
          },
          { title: 'Zinc', name: 'Zinc', amount: 0.0, unit: 'mg' },
          { title: 'Folic Acid', name: 'Folic Acid', amount: 0.0, unit: 'µg' },
          { title: 'Vitamin B3', name: 'Vitamin B3', amount: 0.0, unit: 'mg' },
          { title: 'Vitamin A', name: 'Vitamin A', amount: 0.0, unit: 'IU' },
          { title: 'Vitamin B1', name: 'Vitamin B1', amount: 0.0, unit: 'mg' },
          { title: 'Copper', name: 'Copper', amount: 0.0, unit: 'mg' },
          { title: 'Vitamin B5', name: 'Vitamin B5', amount: 0.0, unit: 'mg' },
          { title: 'Iron', name: 'Iron', amount: 0.01, unit: 'mg' },
          { title: 'Magnesium', name: 'Magnesium', amount: 0.0, unit: 'mg' },
          { title: 'Vitamin E', name: 'Vitamin E', amount: 0.0, unit: 'mg' },
          { title: 'Protein', name: 'Protein', amount: 0.0, unit: 'g' },
          { title: 'Vitamin B6', name: 'Vitamin B6', amount: 0.0, unit: 'mg' },
          { title: 'Sodium', name: 'Sodium', amount: 0.3, unit: 'mg' },
          { title: 'Vitamin D', name: 'Vitamin D', amount: 0.0, unit: 'µg' },
          {
            title: 'Vitamin B12',
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
          },
          {
            title: 'Carbohydrates',
            name: 'Carbohydrates',
            amount: 14.97,
            unit: 'g',
          },
          {
            title: 'Net Carbohydrates',
            name: 'Net Carbohydrates',
            amount: 14.97,
            unit: 'g',
          },
          { title: 'Vitamin B2', name: 'Vitamin B2', amount: 0.0, unit: 'mg' },
          { title: 'Vitamin K', name: 'Vitamin K', amount: 0.0, unit: 'µg' },
          { title: 'Potassium', name: 'Potassium', amount: 0.3, unit: 'mg' },
          { title: 'Alcohol', name: 'Alcohol', amount: 0.0, unit: 'g' },
          { title: 'Sugar', name: 'Sugar', amount: 14.67, unit: 'g' },
          { title: 'Selenium', name: 'Selenium', amount: 0.09, unit: 'µg' },
          { title: 'Folate', name: 'Folate', amount: 0.0, unit: 'µg' },
          { title: 'Manganese', name: 'Manganese', amount: 0.0, unit: 'mg' },
          { title: 'Calcium', name: 'Calcium', amount: 0.15, unit: 'mg' },
          { title: 'Vitamin C', name: 'Vitamin C', amount: 0.0, unit: 'mg' },
        ],
      },
    ],
    caloricBreakdown: {
      percentProtein: 9.68,
      percentFat: 34.54,
      percentCarbs: 55.78,
    },
    weightPerServing: { amount: 151, unit: 'g' },
  },
  summary:
    'Turkish Delight might be just the side dish you are searching for. For <b>78 cents per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. This recipe makes 8 servings with <b>398 calories</b>, <b>10g of protein</b>, and <b>16g of fat</b> each. Not a lot of people made this recipe, and 1 would say it hit the spot. If you have honey, powdered sugar, peanut butter, and a few other ingredients on hand, you can make it. It is a good option if you\'re following a <b>gluten free and vegetarian</b> diet. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 44%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/turkish-delight-lokoom-145635">Turkish Delight (Lokoom)</a>, <a href="https://spoonacular.com/recipes/non-evil-turkish-delight-188466">Non-Evil Turkish Delight</a>, and <a href="https://spoonacular.com/recipes/turkish-delight-vodka-217229">Turkish delight vodka</a> for similar recipes.',
  cuisines: [],
  dishTypes: ['side dish'],
  diets: ['gluten free', 'lacto ovo vegetarian'],
  occasions: [],
  winePairing: {},
  instructions:
    '<ol><li>Measure all ingredients into a large bowl. Stir until well mixed. Spoon into a buttered 12x9-inch pan. Press out mixture to about 1/2-inch thickness. Cut into squares while soft. Cover and refrigerate.</li></ol>',
  analyzedInstructions: [
    {
      name: '',
      steps: [
        {
          number: 1,
          step: 'Measure all ingredients into a large bowl. Stir until well mixed. Spoon into a buttered 12x9-inch pan. Press out mixture to about 1/2-inch thickness.',
          ingredients: [],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
            {
              id: 404645,
              name: 'frying pan',
              localizedName: 'frying pan',
              image: 'pan.png',
            },
          ],
        },
        {
          number: 2,
          step: 'Cut into squares while soft. Cover and refrigerate.',
          ingredients: [],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl: 'https://spoonacular.com/turkish-delight-664089',
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  const { id } = req.query;
  if (!id || id === '') return res.status(200).json({ recipe: null });

  try {
    const data = await fetch(
      `https://api.spoonacular.com/recipes/${id}/information?apiKey=${API_KEY}&includeNutrition=true`
    ).then((res) => (res.status === 200 ? res.json() : null));

    res.status(200).json({ recipe: data });
  } catch (err) {
    return res.status(200).json({ recipe: null });
  }
}
