import type { NextPage } from 'next';
import * as React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [ingredients, setIngredients] = React.useState<Array<string>>([]);
  const [search, setSearch] = React.useState('');
  const router = useRouter();

  const onSearch = async () => {
    router.push(`/search?ingredients=${ingredients.join(',')}`);
  };

  return (
    <>
      <Head>
        <title>Can I Make It</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className={styles.search__full}>
        <input
          className={styles.input}
          type="text"
          placeholder="Add Ingredients"
          value={search}
          onChange={(evt) => setSearch(evt.target.value)}
          onKeyDown={(evt) => {
            if (evt.key === 'Enter') {
              const str = search.trim().toLowerCase();
              if (!ingredients.includes(str) && str !== '')
                setIngredients([...ingredients, str]);
              setSearch('');
            }
          }}
        />

        <button
          className={styles.search__btn}
          type="button"
          onClick={onSearch}
          disabled={ingredients.length === 0}
        >
          What can I make?
        </button>

        <div className={styles.ingredients}>
          <ul className={styles.ingredients__list}>
            {ingredients.map((ingredient) => (
              <li className={styles.ingredients__item} key={ingredient}>
                <button
                  className={styles.remove}
                  onClick={() => {
                    setIngredients(
                      ingredients.filter((val) => val !== ingredient)
                    );
                  }}
                  type="button"
                >
                  X
                </button>

                {ingredient}
              </li>
            ))}
          </ul>
        </div>
      </section>
    </>
  );
};

export default Home;
